config/routes.rb
Rails.application.routes.draw do   
  devise_for :users  
  
  resources :books do
    resources :comments, only: [:create, :destroy, :update]

    member do
      delete 'delete_photo/:photo_id', action: 'delete_photo', as: 'delete_photo'
    end
  end
  
  resources :categories 

  root 'pages#home' 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user) 
    user ||= User.new # guest user (not logged in) 
        
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :author
      can :manage, Book, user_id: user.id                   
    elsif user.has_role? :reviewer
      can :read, Book
      can :manage, Comment, user_id: user.id
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  resourcify
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  resourcify
  searchkick

  belongs_to :user
  belongs_to :category
  
  has_many :comments, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  validates :photo, presence: true, content_type: [:png, :jpg, :jpeg]

  scope :by_category, -> (category_id) { where(category_id: category_id) }
  default_scope { order(title: :asc) }
end

app/models/category.rb
class Category < ApplicationRecord
  resourcify
  has_many :books   
  default_scope { order(category_name: :asc) }  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

   scope :lastest, -> { order('comments.created_at DESC') }

  validates :body, presence: true, allow_blank: false
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  attr_accessor :role

  rolify
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books 
  has_many :comments, dependent: :destroy
 
  after_create :assign_user_role
  validate :validate_username 

  def login
    @login || self.username || self.email
  end  
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end 

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  private

  def assign_user_role
    self.add_role(self.role.parameterize.underscore.to_sym)
  end      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :not_found }
      format.html { redirect_to main_app.root_url, notice: exception.message, status: :not_found }
      format.js   { render nothing: true, status: :not_found }
    end
  end
  
  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :first_name, :last_name, :password, :password_confirmation, :role, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]  
  before_action :set_comment, only: [:show]
  before_action :set_category, only: [:index,:show]  
  load_and_authorize_resource except: [:show]

  def index   
    @books = 
      if params[:category_id]
        Book.by_category(params[:category_id])
      elsif params[:query].present?
        Book.reindex
        @books = Book.search params[:query]              
      elsif current_user.has_role?(:author)
        current_user.books.all
      else
        Book.all                
      end
  end

  def show; end

  def new    
    @book = current_user.books.new
  end  

  def create
    @book = current_user.books.new(book_params)
   
    if @book.save      
      redirect_to @book, notice: 'Book was successfully created.' 
    else
      render :new 
    end      
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.' 
    else
      render :edit
    end  
  end

  def destroy
    if @book.destroy
      redirect_to books_url, notice: 'Book was successfully destroyed.'
    else
      redirect_to root_url, notice: 'Book was not destroyed.'
    end   
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_comment
    @comments = @book.comments.lastest 
  end

  def set_category
    @categories = Category.all          
  end

  def delete_photo
    photo = ActiveStorage::Attachment.find(params[:photo_id])
    if current_user == photo.record || current_user.has_role?(:admin)
      photo.purge
      redirect_back(fallback_location: request.referer)
    else
      redirect_to root_url  
    end
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :description, :photo, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index    
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save        
      redirect_to categories_path, notice: 'Category was successfully created.' 
    else
      render :new 
    end      
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.' 
    else
      render :edit
    end  
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: 'Category was successfully destroyed.'
    else
      redirect_to root_path, notice: 'Category was not destroyed.'
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book  

  def create
    @comment = @book.comments.new(comment_params)

    if @comment.save
      render status: 200, json:{
        comment: render_to_string( partial: 'comments/comment', locals:{ comment: @comment })
      }
    else
      render status: 404, json: { error: @comment.error.full_message.to_sentence }
    end
  end

  def destroy
    @comment = @book.comments.find_by_id(params[:id])

    if @comment.destroy
      render status: 200, json:{ message: "COMMENT DELETED!"}
    else
      render status: 404, json: { error: @comment.errors.full_message.to_sentence }
    end
  end

  def update
    @comment = @book.comments.find_by_id(params[:id])

    if @comment.update(comment_params)
      render status: 200, json:{
        comment: render_to_string(partial: 'comments/comment', locals: { comment: @comment })
      }
    else
      render status:400, json: { error: @comment.errors.full_message.to_sentence }
    end
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
     @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex-row d-flex justify-content-center">
    <div class="col-md-8">
    <div class="card mt-5">
      <div class="card-body">
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, placeholder: "Book Title", class: "form-control"%>  
        </div><br>

        <div class="form-group">
          <% if book.photo.attached? && book.photo.representable? %>
            <%= image_tag(book.photo, width: 150, height: 500, class: "card-img-top") %> 
            <div class="upload-hider-labels">
              <%= link_to '#', class: "replace-upload btn btn-primary" do %>
                Replace current book cover
              <% end %>
              <span class="separator-bar">|</span>
              <%= link_to "Remove Book Cover without replacing", 
                           delete_photo_book_url(photo_id: book.photo.id), 
                           method: :delete, 
                           data: {confirm: "Are you sure?"}, 
                           class: "remove-upload btn btn-primary"
              %>              
            </div>                 
          <% end %> 

            <div class="upload-hider-fields custom-file">
              <%= form.label :photo, class: "custom-file-label" %>       
              <%= form.file_field :photo, class: "form-control", class: "btn btn-outline-primary custom-file-input", id: "file_name" %>
            </div>           
        </div><br>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, placeholder: "Description", class: "form-control" %>          
        </div><br>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.select :category_id, Category.all.map{ |c| [c.category_name, c.id]},{}, {class: "form-control"} %>
        </div>     
      
        <%= form.submit class: "btn btn-outline-primary" %>       
       </div>
    </div>
    </div>
  </div> 
<% end %>

 
            
     <script type="application/javascript">
    
</script>
       

app/views/books/edit.html.erb
<blockquote class="blockquote text-center">
  <h1> Editing Book </h1>
</blockquote>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<blockquote class="blockquote text-center">
  <h1>Books</h1>
</blockquote>

<% if current_user.has_any_role?(:admin, :author) %>                      
  <%= link_to 'New Book', new_book_path, class: "btn btn-outline-primary" %>       
<% end %> 

<div class= "cointainer">
  <div class= "row">    
    <div class="col-md-9">
    <div class= "row">      
      <% @books.each do |book| %>
        <div class= "col-md-5">
        <div class= "card mt-3">          
          <div class= "card-body text-center">           

            <h3> <%= link_to book.title, book_path(book.id) %> </h3> 
            <%= "Author: #{book.user.first_name} #{book.user.last_name}" %> <br />            
            <%= image_tag(book.photo, width: 200, height: 400, class: "card-img-top") %>
            <%=h truncate(book.description, :length => 100, class: "card-text") %> 
            <div class="card-body">
            <%= link_to 'Show', book, class: "btn btn-primary" %>
            <% if current_user.has_any_role?(:admin, :author) %>
              <%= link_to 'Edit', edit_book_path(book), class: "btn btn-primary" %>
              <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary"%>       
            <% end %>
            </div>

        </div>
      </div>
      </div>     
      <% end %>
     </div>
     </div>

    <% if !current_user.has_role?(:author) %>  
      <div class="col-md-3">
      <div class="card mt-3"> 
      <div class="card">
        <div class="card-header">
          Categories
        </div> 

        <div class="card-body">
        <% if !current_user.has_role?(:author) %>
          <% @categories.each do |category| %>         
          <ul class="list-group">
          <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= link_to category.category_name, books_path(category_id: category.id) %>
          <span class="badge badge-primary badge-pill"> <%= category.books.count %></span>
          </li>
          </ul>       
          <% end %>
        <% end %> 
      </div>

      </div>
      </div>      
      </div>
    <% end %>   

  </div>
</div>

app/views/books/new.html.erb
<blockquote class="blockquote text-center">
  <h1>New Book</h1>
</blockquote>

<div>
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="flex-row d-flex justify-content-center"  style="margin: 60px 0 30px 0" >
  <div class="container" >
    <div class="row">
       <div class="col-sm">
        <%= image_tag(@book.photo, width: 300, class: "img-fluid") if @book.photo.attached? %> 
       </div>

       <div class="col-sm">
         <h2> <%= @book.title %> </h2>
         <p>
          <strong>Author:</strong>
          <%= "#{@book.user.first_name} #{@book.user.last_name}"%>
         </p>
         <p>
          <strong>Category:</strong>            
          <%= link_to @book.category.category_name, books_path(category_id: @book.category.id)  %>         
         </p>
         <p>
         <strong>Description:</strong>
         </p> 
         <p>         
         <%= @book.description %> 
         </p>

          <p>
            <% if current_user %>
            <% if current_user.has_any_role?(:admin) %>
              <%= link_to 'Edit Book', edit_book_path(@book) , class: "btn btn-primary" %>
            <% elsif current_user.has_any_role?(:author) && @book.user == current_user %>
              <%= link_to 'Edit Book', edit_book_path(@book) , class: "btn btn-primary" %>
            <% end %>
          <% end %>
          </p>
       </div> 
    </div>  
  </div> 
</div>

  <div class="input-group">
    <% if current_user && current_user.has_role?(:reviewer) %>   
      <textarea class="form-control" name="body"></textarea>
      <%= submit_tag "Leave a review", type: "button", onclick: "submitReview()", class: "btn btn-primary" %>
    <% end %> 
  </div>  

  <div class="container">
    <div class="row justify-content-center">
      <div id = "comment-pane">
        <%= render 'comments/comment_list', collection: @comments %>
      </div>  
    </div>
  </div>    

app/views/categories/_form.html.erb
<%= form_for @category, html: { multipart: true } do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="table-responsive">
   <table class="table">
    <thead>    
    <tr>
      <th scope="row"><%= form.label :category %></th>
      <td><%= form.text_field :category_name, placeholder: "Category Name" %></td>      
    </tr>
    </thead>
    </table> 
  </div> 
  <div> 
    <%= form.submit class: "btn btn-outline-primary" %>
  </div> 
<% end %>

app/views/categories/edit.html.erb
<blockquote class="blockquote text-center">
<h1>Editing Category</h1>
</blockquote>
<%= render 'form', category: @category %>
<br />
<%= link_to 'Show', @category %>

app/views/categories/index.html.erb
<blockquote class="blockquote text-center">
<h1>Categories</h1>
</blockquote>

<table class="table-responsive">
  <thead>
    <tr>      
      <th scope="col">Category</th>       
    </tr>
  </thead>
   <tbody>
    <% @categories.each do |category| %>
      <tr>             
        <td><%= category.category_name %></td>               
        <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary"%> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Category', new_category_path %>
<br />

app/views/categories/new.html.erb
<blockquote class="blockquote text-center">
  <h1>New Category</h1>
</blockquote>  
<%= render 'form', category: @category %>
<br />

app/views/categories/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @category.category_name %>
</p>

app/views/comments/_comment.html.erb
<div class="container">
  <div class="dialogbox">
    
    <div class="body">     
      <span class="tip tip-up"></span>
      <div class="message">
        <span>
          
          <div id = "<%= comment.id %>">    
            <b><%= "#{comment.user.first_name} #{comment.user.last_name} "%></b>
            <%= comment.created_at.strftime("reviewed on %m/%d/%Y: ") %></br>
            <%= comment.body %> 

            <% if current_user %>
              <% if current_user.has_role?(:admin) || current_user == comment.user %>  
                <button type="button" onclick="deleteComment(<%= comment.id %>)" class= "btn btn-outline-light btn-sm" > Delete
                </button>   
                <button type="button" onclick="editComment(<%= comment.id %>)" class= "btn btn-outline-light btn-sm"> Edit </button>
              <% end %>
            <% end %>    
          </div>

        </span>
      </div>      
    </div>
   

  </div>
</div>


  

app/views/comments/_comment_list.html.erb
<div id = "inputEdit"></div>
<div class="container">
  <div class="dialogbox">
    <% @comments.each do |comment| %>  
    <div class="body">     
      <span class="tip tip-up"></span>
      <div class="message">        
        <span>         
          <div id = "<%= comment.id %>">    
            <b><%= "#{comment.user.first_name} #{comment.user.last_name} "%></b>
            <%= comment.created_at.strftime("reviewed on %m/%d/%Y: ") %><br />
            <%= comment.body %>  <br />

            <% if current_user %>
              <% if current_user.has_role?(:admin) || current_user == comment.user %>  
                <button type="button" onclick="deleteComment(<%= comment.id %>)" class= "btn btn-outline-light btn-sm" > Delete
                </button>   
                <button type="button" onclick="editComment( <%= comment.id %>)" class= "btn btn-outline-light btn-sm"> Edit </button>
              <% end %>
            <% end %>    
          </div>

        </span>
      </div>      
    </div>
    <% end %>

  </div>
</div>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mybook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <p style="margin-top: 0.75em;" class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p style="margin-top: 0.75em;" class="alert alert-danger"><%= notice %></p>
      <% end %>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container">
        <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link text-light' %>
          </li>
        </ul>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-md-auto">
            <% if current_user %>
              <% if current_user.has_role?(:admin) %>
                <li class="nav-item">
                  <%= link_to 'Categories', categories_path, class: "nav-link text-light" %>
                </li>
              <% end %>

              <li class="nav-item">        
                <%= link_to 'Books', books_path, class: "nav-link text-light" %>
              </li>

              <li class="nav-item">
                <%= link_to 'Update Profile', edit_user_registration_path, method: :get, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: "nav-link text-light" %>
              </li>
            <% end %> 
          </ul>        

          <div>
            <%= form_tag "/books", method: :get, class: "form-inline my-2 my-lg-0" do %>
              <%= text_field_tag "query", params[:query], class: "form-control mr-sm-2" %>
              <%= submit_tag "Search", class: "btn btn-outline-warning my-2 my-sm-0" %>
            <% end %>
          </div>
        </form>        
        </div>

        
      </div>
      </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html> 

app/views/pages/home.html.erb
<div style="margin: 60px 0 30px 0">
  <% if @books %>
    <div class="row">
      <% @books.each do |book| %>
        <div style="margin-bottom: 30px;" class="col-sm-4">
          <div class="card" style="width: 100%;">
             <% if book.photo.attached? && book.photo.representable? %>                         
              <%= image_tag(book.photo, width: 200, height: 400, class: "card-img-top") %>             
            <% else %>
              <img class="card-img-top" src="//cdn.jpegmini.com/user/images/slider_puffin_before_mobile.jpg">
            <% end %>

            <div class="card-body">
              <h5 class="card-title"><%= book.title %></h5>              
              <%=h truncate(book.description, :length => 100, class: "card-text") %>
              <%= link_to "Read more", book_url(book), class: "text-warning" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>